### PR TITLE
Update members list & news date bugfix

### PR DESCRIPTION
**Pull request by begonaalvarezd**
- Remove Akita & Accessec from members list
- Bufix News date month starting at number 0

### CODE REVIEW

**Comment by autumnfound** [comment]
Code LGTM. Signoff is a minor sticking point though.

Small question, is there a semantic reason to remove trailing commas in React? I know most people prefer to have them as a convention thing when possible.

**Comment by begonaalvarezd** [comment]
@autumnfound My bad about the signature, I am going to fix it right away. 
The trailing commas got removed because of a parasite prettier configuration I had in the workspace. Let me fix that also.

**Comment by begonaalvarezd** [comment]
@autumnfound everything should be fine now. If you agree I will merge.

**Review by autumnfound — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
